import { ElementRef, EventEmitter, OnDestroy, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import { Subscription } from 'rxjs';
export declare class SearchBoxWidgetComponent implements OnInit, OnDestroy {
    faSearch: import("@fortawesome/fontawesome-common-types").IconDefinition;
    faTimes: import("@fortawesome/fontawesome-common-types").IconDefinition;
    initKeyword: string;
    formClass: string;
    inputClass: string;
    prependText: string;
    debounceTime: number;
    minLength: number;
    onSearch: EventEmitter<void>;
    searchControlElem: ElementRef;
    searchControl: FormControl;
    anyFutureKeyword: string;
    effectiveKeyword: string;
    _searchKeywordSubr: Subscription;
    private _emitEvent;
    constructor();
    set emitEvent(v: boolean);
    get emitEvent(): boolean;
    ngOnInit(): void;
    ngOnDestroy(): void;
    cancelTypedKeyword(): void;
    kickOffSearch(): void;
    resetKeyword(emitEvent?: boolean): void;
    startObserveSearchKeyword(): void;
    stopObserveSearchKeyword(): void;
}
